name: publish
on:
  push:
    branches: 
      - master
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: build image
        run: |
          docker build . -t localhost:5000/horni/setcolour
          docker push localhost:5000/horni/setcolour

      - name: checkout repository
        uses: actions/checkout@v2

      - name: create namespace cert-manager
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: create namespace cert-manager

      - name: install helm repo jetstack
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm repo add jetstack https://charts.jetstack.io
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: update cert-manager helm repo
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm repo update
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: install cert-manager helm repo
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm install cert-manager jetstack/cert-manager --namespace cert-manager --version v0.15.1 --set installCRDs=true
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: set k8s context
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: deploy k8s  
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            k8s/setcolour.yaml
            k8s/service.yaml
            k8s/ingress.yaml
            k8s/tls.yaml
            k8s/cert.yaml
     