name: docker
on:
  push:
    branches: 
      - master
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Publish Image
      uses: matootie/github-docker@v2.2.2
      with:
        accessToken: ${{ secrets.GITHUB_TOKEN }}
 
