name: publish
on:
  push:
    branches: 
      - master
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: build image
        run: |
          docker build . -t localhost:5000/horni/setcolour
          docker push localhost:5000/horni/setcolour

      - name: checkout repository
        uses: actions/checkout@v2

      - name: set k8s context
        uses: Azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: deploy k8s  
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            k8s/setcolour.yaml
            k8s/service.yaml
            k8s/ingress.yaml
            k8s/tls.yaml
            k8s/cert.yaml

     